# -*- coding: utf-8 -*-
"""ProjectX5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpeKvrqzjjw_g6bEH47a57BjcR1SVnWm
"""

from google.colab import drive
drive.mount('/content/drive/')

import os
import numpy as np
import pickle
from tqdm import tqdm

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, BatchNormalization, ReLU
from tensorflow.keras.layers import GlobalAveragePooling1D, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.utils import to_categorical

MAX_FRAMES = 60         # half avardhanam frames
FEATURES = 132          # keypoints per frame
NUM_CLASSES = 7         # number of adavus
DATA_ROOT = "/content/drive/MyDrive/BharatanatyamKeypoints"  # CHANGE this

label_map = {
    'thattadavu': 0,
    'paravaladavu': 1,
    'circleadavu': 2,
    'kuthadavu': 3,
    'nattadavu': 4,
    'theermanam': 5,
    'kuthithemetadavu': 6
}
id_to_label = {v: k for k, v in label_map.items()}

def create_windows(seq, window_size=MAX_FRAMES, step=10):
    windows = []
    for i in range(0, len(seq) - window_size + 1, step):
        windows.append(seq[i:i+window_size])
    return windows

def fix_sequence_length(seq, max_frames=MAX_FRAMES):
    T = seq.shape[0]
    if T > max_frames:
        return seq[:max_frames]
    elif T < max_frames:
        pad_len = max_frames - T
        pad = np.repeat(seq[-1][None, :], pad_len, axis=0)
        return np.vstack([seq, pad])
    return seq

def normalize_relative(X):
    X = X.copy()
    for i in range(X.shape[0]):
        center = X[i,:,0:2].mean(axis=1, keepdims=True)
        X[i,:,0:2] -= center
    return X

def augment_sequence(seq):
    seq = seq.copy()
    # Horizontal flip
    if np.random.rand() < 0.5:
        seq[:, 0::4] *= -1
    # Small noise
    if np.random.rand() < 0.5:
        seq += np.random.normal(0, 0.01, seq.shape)
    # Small temporal shift
    if np.random.rand() < 0.3:
        seq = np.roll(seq, np.random.randint(-2,3), axis=0)
    return seq

X, y_raw = [], []

for adavu_name in tqdm(os.listdir(DATA_ROOT)):
    adavu_path = os.path.join(DATA_ROOT, adavu_name)
    if not os.path.isdir(adavu_path):
        continue
    for variation in os.listdir(adavu_path):
        var_path = os.path.join(adavu_path, variation)
        for speed in os.listdir(var_path):
            speed_path = os.path.join(var_path, speed)
            for file in os.listdir(speed_path):
                if file.endswith(".npy"):
                    seq = np.load(os.path.join(speed_path, file))
                    # create sliding windows per video
                    windows = create_windows(seq, MAX_FRAMES, step=10)
                    for w in windows:
                        X.append(w)
                        y_raw.append(adavu_name)

X = np.array(X, dtype=np.float32)
y = np.array([label_map[label] for label in y_raw], dtype=np.int32)

print("Total samples:", X.shape[0], "X shape:", X.shape, "y shape:", y.shape)

# Normalize
X = normalize_relative(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

y_train_cat = to_categorical(y_train, NUM_CLASSES)
y_test_cat  = to_categorical(y_test, NUM_CLASSES)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weights = dict(enumerate(class_weights))

def build_tcn_model():
    model = Sequential([
        Conv1D(128, kernel_size=3, padding='causal', activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001), input_shape=(MAX_FRAMES, FEATURES)),
        BatchNormalization(),
        Dropout(0.3),

        Conv1D(64, kernel_size=3, padding='causal', activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
        BatchNormalization(),
        Dropout(0.3),

        Conv1D(32, kernel_size=3, padding='causal', activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
        BatchNormalization(),
        Dropout(0.2),

        GlobalAveragePooling1D(),
        Dense(64, activation='relu'),
        Dropout(0.3),
        Dense(NUM_CLASSES, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

model = build_tcn_model()
model.summary()

checkpoint = ModelCheckpoint("best_tcn_adavu_model.h5", monitor='val_accuracy', save_best_only=True, verbose=1)
early_stop = EarlyStopping(monitor='val_accuracy', patience=10, restore_best_weights=True, verbose=1)

history = model.fit(
    X_train, y_train_cat,
    validation_split=0.1,
    epochs=60,
    batch_size=32,
    class_weight=class_weights,
    callbacks=[checkpoint, early_stop],
    verbose=1
)

loss, acc = model.evaluate(X_test, y_test_cat)
print("Test Accuracy:", acc)

with open("label_map.pkl", "wb") as f:
    pickle.dump(label_map, f)

print("TCN model and label_map saved!")

MODEL_PATH = "/content/drive/MyDrive/best_tcn_adavu_model.h5"
LABEL_PATH = "/content/drive/MyDrive/label_map.pkl"

