# -*- coding: utf-8 -*-
"""ProjectX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YElE0dVQ-Q2wZi1fo7eWhbTRSXrn1Dkz
"""

!pip install mediapipe opencv-python numpy tqdm

import cv2
import mediapipe as mp
import numpy as np
import os
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

mp_pose = mp.solutions.pose

pose = mp_pose.Pose(
    static_image_mode=False,
    model_complexity=1,      # balanced (fast + accurate)
    smooth_landmarks=True,
    enable_segmentation=False,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

DATASET_DIR = "/content/drive/MyDrive/Data"
OUTPUT_DIR  = "/content/drive/MyDrive/BharatanatyamKeypoints"

os.makedirs(OUTPUT_DIR, exist_ok=True)

!cp -r "/content/drive/MyDrive/Data" /content/dataset

DATASET_DIR = "/content/dataset"

def extract_pose_keypoints(video_path, target_fps=25):
    cap = cv2.VideoCapture(video_path)

    original_fps = cap.get(cv2.CAP_PROP_FPS)
    frame_skip = max(int(original_fps // target_fps), 1)

    keypoints_sequence = []
    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        if frame_count % frame_skip != 0:
            continue

        frame = cv2.resize(frame, (1280, 720))
        image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = pose.process(image_rgb)

        if results.pose_landmarks:
            frame_keypoints = []
            for lm in results.pose_landmarks.landmark:
                frame_keypoints.extend([lm.x, lm.y, lm.z, lm.visibility])
            keypoints_sequence.append(frame_keypoints)

    cap.release()
    return np.array(keypoints_sequence)  # (T, 132)
video_files = []

for root, _, files in os.walk(DATASET_DIR):
    for file in files:
        if file.lower().endswith(".mp4"):
            video_files.append(os.path.join(root, file))

print(f"Total videos found: {len(video_files)}")
processed = 0
skipped = 0

for video_path in tqdm(video_files, desc="Processing videos"):
    relative_path = os.path.relpath(video_path, DATASET_DIR)
    save_path = os.path.join(
        OUTPUT_DIR,
        relative_path.replace(".mp4", ".npy")
    )

    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    # 🔒 RESUME-SAFE LOGIC
    if os.path.exists(save_path):
        skipped += 1
        continue

    keypoints = extract_pose_keypoints(video_path)

    if keypoints.shape[0] < 10:
        continue  # skip broken/too short clips

    np.save(save_path, keypoints)
    processed += 1

print(f"Newly processed: {processed}")
print(f"Skipped (already done): {skipped}")